### PR TITLE
Update 2023-04-05-finsum_flant5_base_en.md

### PR DESCRIPTION
**Pull request by gadde5300**
Updated description for T5 models

### CODE REVIEW

**Review by dcecchini — CHANGES_REQUESTED** [review]
Change `Google AI` to `Google researchers`. Can you add the reference paper? If so, please cite this one:

```
Chung, Hyung Won, et al. "Scaling instruction-finetuned language models." arXiv preprint arXiv:2210.11416 (2022).
```

With the link: https://arxiv.org/abs/2210.11416

**Comment by gadde5300** [comment]
> Change `Google AI` to `Google researchers`. Can you add the reference paper? If so, please cite this one:
> 
> ```
> Chung, Hyung Won, et al. "Scaling instruction-finetuned language models." arXiv preprint arXiv:2210.11416 (2022).
> ```
> 
> With the link: https://arxiv.org/abs/2210.11416

Hi, I have updated the description by adding a citation in it, If that is good, then I will add them to the remaining 2 markdown files too.

**Review by dcecchini — CHANGES_REQUESTED** [review]
Please add it like the following (add the `References` part, use `bibtex` code syntax instead of markdown, add the bibtex reference):

References:

```bibtex
@article{flant5_paper,
  title={Scaling instruction-finetuned language models},
  author={Chung, Hyung Won and Hou, Le and Longpre, Shayne and Zoph, Barret and Tay, Yi and Fedus, William and Li, Eric and Wang, Xuezhi and Dehghani, Mostafa and Brahma, Siddhartha and others},
  journal={arXiv preprint arXiv:2210.11416},
  year={2022}
}

@article{t5_paper,
  title={Exploring the limits of transfer learning with a unified text-to-text transformer},
  author={Raffel, Colin and Shazeer, Noam and Roberts, Adam and Lee, Katherine and Narang, Sharan and Matena, Michael and Zhou, Yanqi and Li, Wei and Liu, Peter J},
  journal={The Journal of Machine Learning Research},
  volume={21},
  number={1},
  pages={5485--5551},
  year={2020},
  publisher={JMLRORG}
}
```

**Comment by gadde5300** [comment]
Hi David, Good Morning!
I have updated the description of all 3 PR's.

**Pull request merged**
